/**
 * Single source of truth for all skill/keyword definitions.
 *
 * A skill entry can be either:
 * - a plain string (canonical name), e.g. "java"
 * - an array where the first item is the canonical name and the rest are aliases,
 *   e.g. ["javascript", "js", "es6"]
 *
 * Matching is done by scanning the input text for the canonical name or any alias.
 */

export type SkillList = (string | string[])[];

export type CategorySkills = Record<string, SkillList>;

/**
 * Technical / hard skills, grouped by category.
 */
export const SKILLS: CategorySkills = {
  programmingLanguages: [
    ["javascript", "js", "es6", "es2015", "ecmascript"],
    ["typescript", "ts"],
    ["python", "py"],
    "java",
    "c++",
    "c#",
    "go",
    "rust",
    ["ruby", "rb"],
    "php",
    "swift",
    "kotlin",
    "scala",
    "r",
    "sql",
    "dart",
    "shell",
    "bash",
  ],

  frontendFrameworks: [
    ["react", "reactjs", "react.js"],
    ["angular", "angularjs", "angular.js"],
    ["vue", "vuejs", "vue.js"],
    "svelte",
    ["next.js", "nextjs", "next"],
    "nuxt",
    "gatsby",
    "remix",
    "solid",
    "qwik",
  ],

  backendFrameworks: [
    ["express", "expressjs", "express.js"],
    "fastify",
    "nestjs",
    "django",
    "flask",
    "fastapi",
    "spring",
    "rails",
    "laravel",
    "asp.net",
    "gin",
    "fiber",
    ["nodejs", "node.js", "node"],
  ],

  databases: [
    ["mongodb", "mongo"],
    ["postgresql", "postgres"],
    "mysql",
    "redis",
    "sqlite",
    "elasticsearch",
    "dynamodb",
    "cassandra",
    "mariadb",
    "oracle",
    "mssql",
    "nosql",
    "firebase",
    "supabase",
  ],

  orms: [
    "prisma",
    "mongoose",
    "sequelize",
    "typeorm",
    "drizzle",
    "hibernate",
    "entity framework",
  ],

  cloudPlatforms: [
    "aws",
    "azure",
    "gcp",
    "digitalocean",
    "heroku",
    "vercel",
    "netlify",
    "cloudflare",
  ],

  devopsTools: [
    "docker",
    ["kubernetes", "k8s"],
    "jenkins",
    "gitlab ci",
    ["github actions", "gh actions"],
    "circleci",
    "ansible",
    ["terraform", "tf"],
    "prometheus",
    "grafana",
    "datadog",
    "new relic",
  ],

  testingTools: [
    "jest",
    "mocha",
    "cypress",
    "playwright",
    "selenium",
    "vitest",
    "testing library",
    "jasmine",
    "pytest",
    "junit",
    "postman",
  ],

  versionControl: ["git", "github", "gitlab", "bitbucket"],

  methodologies: [
    "agile",
    "scrum",
    "kanban",
    "devops",
    "ci/cd",
    "tdd",
    "bdd",
    "microservices",
    "serverless",
    "event-driven",
    "rest",
    "graphql",
  ],
};

/**
 * Soft skills. Includes the extra soft skills previously defined only in jdParser.
 */
export const SOFT_SKILLS: SkillList = [
  ["leadership", "leader", "team lead"],
  ["communication", "communications"],
  "teamwork",
  ["problem solving", "problem-solving"],
  ["critical thinking", "critical-thinking"],
  ["time management", "time-management"],
  "adaptability",
  "collaboration",
  "mentoring",
  "presentation",
  ["negotiation", "negotiating"],
  ["conflict resolution", "conflict-resolution"],
  "creativity",
  "initiative",
  ["self-motivated", "self motivated", "self-motivation"],
  ["detail-oriented", "detail oriented"],
  "organization",
  "ownership",
  "attention to detail",
  "analytical",
];

/**
 * Action verbs in base form. Matching also catches inflected forms
 * (e.g. "develop" matches "developed", "developing").
 */
export const ACTION_VERBS: string[] = [
  "develop",
  "design",
  "implement",
  "architect",
  "engineer",
  "program",
  "code",
  "debug",
  "test",
  "deploy",
  "lead",
  "manage",
  "direct",
  "supervise",
  "mentor",
  "coordinate",
  "facilitate",
  "guide",
  "train",
  "delegate",
  "optimize",
  "improve",
  "enhance",
  "refactor",
  "streamline",
  "automate",
  "modernize",
  "upgrade",
  "migrate",
  "create",
  "build",
  "establish",
  "found",
  "initiate",
  "launch",
  "introduce",
  "pioneer",
  "conceptualize",
  "analyze",
  "evaluate",
  "assess",
  "investigate",
  "research",
  "identify",
  "diagnose",
  "audit",
  "communicate",
  "present",
  "document",
  "report",
  "collaborate",
  "negotiate",
  "persuade",
  "influence",
  "achieve",
  "deliver",
  "exceed",
  "accomplish",
  "attain",
  "secure",
  "win",
  "earn",
  "maintain",
  "write",
  "solve",
  "integrate",
  "monitor",
  "support",
  "own",
  "review",
  "ensure",
  "scale",
];

/**
 * Industry-specific keywords grouped by domain. Used for keyword matching
 * in both JD parsing and resume parsing.
 */
export const KEYWORDS: CategorySkills = {
  softwareDevelopment: [
    "sdlc",
    "code review",
    "version control",
    "branching",
    "merging",
    "pull request",
    "continuous integration",
    "continuous deployment",
    "api",
    "microservice",
    "monolith",
    "serverless",
    "cloud-native",
  ],
  webDevelopment: [
    "responsive",
    "spa",
    "ssr",
    "ssg",
    "pwa",
    "seo",
    "accessibility",
    "wcag",
    "cross-browser",
    "mobile-first",
    "performance optimization",
  ],
  dataEngineering: [
    "etl",
    "data pipeline",
    "data warehouse",
    "data lake",
    "big data",
    "streaming",
    "batch processing",
    "data modeling",
    "data governance",
  ],
  machineLearning: [
    "machine learning",
    "deep learning",
    "neural network",
    "nlp",
    "cv",
    "model training",
    "feature engineering",
    "hyperparameter tuning",
  ],
  cybersecurity: [
    "security",
    "encryption",
    "authentication",
    "authorization",
    "oauth",
    "jwt",
    "ssl",
    "tls",
    "penetration testing",
    "vulnerability assessment",
  ],
  projectManagement: [
    "stakeholder",
    "roadmap",
    "milestone",
    "deliverable",
    "sprint",
    "backlog",
    "retrospective",
    "standup",
    "planning",
    "estimation",
  ],
};
