export const CATEGORY_WEIGHTS = {
  hardSkills: 40,
  searchability: 25,
  formatting: 15,
  softSkills: 10,
  recruiterTips: 10,
} as const;

// NOTE: maybe engineer and developer should be removed
export const TITLE_STOPWORDS = new Set([
  "the",
  "and",
  "for",
  "with",
  "of",
  "in",
  "on",
  "at",
  "to",
  "a",
  "an",
  "is",
  "role",
  "position",
  "opportunity",
  "job",
  "engineer",
  "developer",
  "specialist",
  "lead",
  "senior",
  "junior",
  "entry",
  "level",
]);

export const ROLE_NOUNS =
  /\b(engineer|developer|designer|manager|director|specialist|analyst|consultant|architect|scientist|researcher|writer|tester|coordinator|administrator|officer|executive|lead)\b/i;

export const ATS_DATE_RE =
  /^(present|current|now|ongoing|\d{1,2}\/\d{2}(\d{2})?|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s?\d{4})$/i;

export const MEASURABLE_RESULT_RE =
  /(?:\d+(?:\.\d+)?%|\d+(?:\.\d+)?x|\$\s?\d+(?:,\d{3})*(?:\.\d+)?[KMB]?|\d+(?:,\d{3})*(?:\.\d+)?[KMB]?\+?|\d+\s*(?:hours?|hrs?|days?|weeks?|months?|years?)|(?:team of|managed|led|supervised)\s+\d+|\d+\s*(?:members?|people|employees?|clients?|users?|customers?)|\d+(?:\.\d+)?\/\d+)/i;

/**
 * Common resume action verbs (past tense) used to score how action-oriented
 * the work experience bullet points are. Matched with word boundaries.
 */
export const ACTION_VERBS: string[] = [
  "accelerated",
  "accomplished",
  "achieved",
  "architected",
  "automated",
  "boosted",
  "built",
  "championed",
  "collaborated",
  "communicated",
  "completed",
  "conducted",
  "configured",
  "coordinated",
  "crafted",
  "created",
  "customized",
  "debugged",
  "defined",
  "delivered",
  "deployed",
  "designed",
  "developed",
  "directed",
  "documented",
  "established",
  "evaluated",
  "executed",
  "expanded",
  "facilitated",
  "generated",
  "guided",
  "handled",
  "implemented",
  "improved",
  "increased",
  "initiated",
  "innovated",
  "integrated",
  "introduced",
  "launched",
  "led",
  "maintained",
  "managed",
  "mentored",
  "migrated",
  "modernized",
  "negotiated",
  "operated",
  "optimized",
  "orchestrated",
  "organized",
  "performed",
  "planned",
  "produced",
  "programmed",
  "provided",
  "published",
  "reduced",
  "refactored",
  "resolved",
  "revamped",
  "scaled",
  "scheduled",
  "secured",
  "shipped",
  "simplified",
  "solved",
  "spearheaded",
  "streamlined",
  "strengthened",
  "supervised",
  "tested",
  "trained",
  "transformed",
  "upgraded",
  "wrote",
];

//  measurable result er scoring kuthtai kora hoyeche location bolo - ki approach follow kora hoyech ebolo bangliss e  